version: 2.1
orbs:
  node: circleci/node@4.9.0
  docker: circleci/docker@0.5.19
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - docker/install-docker
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: env
      - node/install-packages
      - run: npm install --no-save tap-xunit
      - run:
          name: spinning up ganache
          command: npm run start:eth
          background: true
      - run: npm test --  --timeout=5m --tap --no-color > _out/unit/test.xml
      - run: npm run build
      - store_test_results:
          path: _out
      - store_artifacts:
          path: _out

  build-and-release-to-staging:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - docker/install-docker
      - run: ./create-version-file.sh
      - node/install-packages
      - run: npm install --no-save tap-xunit
      - run: npm test
      - run: npm run build
      - run: ./docker-build.sh
      - run: ./.circleci/release-to-staging.sh

workflows:
  build-and-release:
    jobs:
      - build-and-release-to-staging:
          filters:
            branches:
              only: /.*/
            tags:
              only: /v.*/
